# Generated by Django 4.2.4 on 2023-12-21 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institucion',
            old_name='nombre',
            new_name='nombre_intitucion',
        ),
    ]
